version: "3"

services:
  db:
    image: mysql:8.0.33
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      TZ: ${TZ}
    ports:
        - ${DB_PORT}:3306
    volumes:
        - db-store:/var/lib/mysql
        - ./mysql/conf/my.cnf:/etc/mysql/conf.d/my.cnf
        - ./mysql/sql:/docker-entrypoint-initdb.d
  app:
    image: stock-manager
    container_name: stock
    build:
      context: ./app
    restart: always
    ports:
        - 80:80
        - 443:443
    environment: 
      Database__DatabaseName: ${DB_NAME}
      ConnectionStrings__Database: Server=db;Port=3306;UserID=${DB_USER};Password=${DB_PASS};Database=${DB_NAME};IgnoreCommandTransaction=true;

volumes:
  db-store: